dags/config/ingestion/chartmaxx_config.json
* Set run_type to initial
* Set cluster_type to large
=> test: UNIC-622 Debug curated chartmaxx

dags/config/enriched/mfm_config.json, dags/spark_operators.py
- Add step for MFM published tables in enriched DAG
- Small refactoring of default args in `generic_job()`
=> feat: UNIC-703 MFM green published tables

dags/config/warehouse/unic_config.json
- `warehouse_fetal_ultra_sound`
- `warehouse_pathology`
=> fix: UNIC-708 Add missing warehouse ETLs

dags/config/ingestion/softpath_config.json, dags/config/warehouse/unic_config.json
- Increase `anonymized_softpath_v_p_pat_specimen` cluster type to medium
- Remove `warehouse_pathology` custom worker ram spec
=> Perf: UNIC-722 Change cluster settings for softpath

dags/config/ingestion/etraceline_config.json
Run anonymized etraceline `patient` and `test_request_l` in initial to fix schema merging issue
=> fix: UNIC-733 Run anonymized etraceline patient + test_request_l in initial

dags/config/ingestion/pharmacie_config.json
Anonymized pharmacie phfprescript has to be rerun since new column `PRES_ALLOW_ADD_BOLUS` has been added.
=> fix: Remove unnecessary regex + run pharmacie phfprescript in initial medium

dags/config/enriched/coda_config.json, dags/config/enriched/coprema_config.json, dags/config/enriched/mfm_config.json, dags/config/warehouse/unic_config.json
+ Add published coda dags
+ Add mfm_labour_and_birth_complications
+ Add warehouse_diagnostic_reference
+ Increase dag concurrency
=> feat: UNIC-779 Add published coda + mfm_labour_and_birth_complications

dags/config/enriched/coda_config.json, dags/config/ingestion/laboratoire_systeme_config.json, dags/config/ingestion/opera_config.json, dags/config/ingestion/pericalm_config.json, dags/config/ingestion/pharmacie_config.json, dags/config/ingestion/radimage_config.json, dags/config/ingestion/softpath_config.json
- Change ingestion schedules according to IT schedule file
- Set published_coda_observation_labs to medium for performance
=> fix: Change schedule for IT

dags/config/ingestion/softpath_config.json
Runtime was > 45 min for table ingestion
=> perf: Set softpath specimen cluster type to medium

dags/anonymized_participant_index.py
Reverts Ferlab-Ste-Justine/unic-dag#281
=> Revert "chore: UNIC-1131 Set anonymized participant index signature to initial"

dags/enriched_signature.py
* Add released signature tasks
* Create enriched and released task groups
* Create global start and end tasks for Slack notifications
=> feat: UNIC-1134 Add released signature group and tasks

dags/config/ingestion/pericalm_config.json
Reverts Ferlab-Ste-Justine/unic-dag#302
=> Revert "chore: UNIC-1169 Run anonymized pericalm in initial to clean Ids"

dags/poc_email.py
Reverts Ferlab-Ste-Justine/unic-dag#314
=> Revert "poc: UNIC-1135 Test SSL and TLS false for EmailOperator"

dags/config/ingestion/pericalm_config.json
Reverts Ferlab-Ste-Justine/unic-dag#309
=> Revert "chore: UNIC-1186 Set curated pericalm to initial"

dags/enriched_signature.py
+ Set skip_last_visit_survey to True
=> feat(signature): UNIC-1135 Format email html content

dags/config/anonymized/eclinibase_config.json
Reverts Ferlab-Ste-Justine/unic-dag#412
=> Revert "chore: Run eclinibase v_identification_adresse with medium-initial"

dags/enriched_indicateurssip.py
Reverts Ferlab-Ste-Justine/unic-dag#516
=> Revert ":adhesive_bandage: fix: Set published indicateurssip to initial"

dags/config/yellow/warehouse/unic_config.json
Reverts Ferlab-Ste-Justine/unic-dag#513
=> Revert ":wrench: chore: UNIC-1367 Set warehouse lab results run type to initial"

dags/config/red/ingestion/softlab_config.json
Reverts Ferlab-Ste-Justine/unic-dag#522
=> Revert ":adhesive_bandage: fix(softlab): UNIC-1384 Remove UpdateLog step to prevent data deletion"

dags/config/yellow/warehouse/unic_config.json
Reverts Ferlab-Ste-Justine/unic-dag#524
=> Revert ":adhesive_bandage: fix: UNIC1383 Set warehouse_lab_results to initial to fix missing data"

dags/config/red/curated/medecho_config.json
Reverts Ferlab-Ste-Justine/unic-dag#534
=> Revert ":lock: chore: UNIC-1392 Run medecho as initial to clean postal codes"

dags/config/yellow/warehouse/unic_config.json
Reverts Ferlab-Ste-Justine/unic-dag#551
=> Revert ":wrench: fix: Run warehouse family medical history as initial to reset schema"

dags/config/yellow/anonymized/viewpoint6_config.json
En attente de https://github.com/Ferlab-Ste-Justine/unic-etl/pull/800 avant de merger
=> :wrench: chore: UNIC-1423 Update vp6 conf + Add new table

dags/config/red/ingestion/softpath_config.json
Reverts Ferlab-Ste-Justine/unic-dag#592
=> Revert " :alembic: debug: UNIC-1427 Disable softpath publish class to investigate db"

dags/curated_quanumchartmaxx.py
Reverts Ferlab-Ste-Justine/unic-dag#682
=> Revert ":construction: Debug curated quanum empty table"

dags/enriched_indicateurssip.py, dags/postgres_indicateurs_sip.py, dags/sql/indicateurs_sip/tables/drop_tables.sql, dags/sql/indicateurs_sip/tables/infirmieres_schema.sql, dags/sql/indicateurs_sip/tables/sejour_schema.sql
modify schema of tables sejour and infirmieres + add new tables to enriched_indicateurssip.py
=> UNIC-1483: indicateurs sip

dags/enriched_indicateurssip.py, dags/lib/config.py, dags/lib/tasks/excel.py, dags/postgres_catalog_load_metadata_from_excel.py, docker-compose.yaml, requirements.txt
* Create Postgres Catalog Load Metadata from Excel DAG
* Add excel_to_csv task
* Add openpyxl to docker-compose
* Update requirements file
=> :sparkles: feat: UNIC-1512 Create Postgres Catalog Load Metadata from Excel DAG

dags/postgres_catalog_load_metadata_from_excel.py
Reverts Ferlab-Ste-Justine/unic-dag#769
=> Revert ":bug: debug: Test green minio conn id instead of yellow"

dags/anonymized_philips.py
- Created a temporary DAG `anonymized_philips` to anonymize data from Philips
- The DAG will backfill data from 2023-08-15 up to today
- This is a temp solution later on it'll be embedded into the daily dag for Philips
=> :construction: feat: add new dag to anonymize data from Philips

dags/config/red/ingestion/softlab_config.json
Reverts Ferlab-Ste-Justine/unic-dag#1044
=> Revert ":wrench: chore: UNIC-1703 Set anonymized softlab order to initial"

dags/config/red/ingestion/softlab_config.json
This reverts commit e85b67e3034f58e0bf09bb6931218e8aed645eab.
=> Revert ":wrench: chore(softlab): run v_p_lab_patient in initial (#1055)"

dags/enriched_sprintkid.py
This reverts commit 7f3bc1de2790169b2bbf6582133bc021427f6072.
=> Revert ":wrench: chore(sprkingkid): rerun enriched in initial -- new partition

dags/config/red/curated/pharmacie_config.json
Table removed from post_tests is `anonymized_pharmacie_phfprescripteur_objetprecrivable_champsadditionnels_lstelement`
=> :white_check_mark: fix: Pharmacie pre_tests + Remove upsert table from post_tests

dags/enriched_cpip.py, dags/enriched_promptbolus.py
Reverts Ferlab-Ste-Justine/unic-dag#1152
=> Revert ":wrench: chore: Set enriched cpip + promptbolus to initial for reportCreationDate new col"
